#!/bin/bash
HOST=https://nhutil-sandbox.mxapps.io
ENDPOINT=/rhtest
URL="$HOST$ENDPOINT?cmd=exec&args=ex02();"
CURL=curl
SRC=./res/biojava.js
$CURL \
	--insecure \
	$URL \
	-H "Content-type: application/javascript" \
	--data-binary @$SRC \
	--output -
